//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.20 at 02:18:24 PM CST 
//


package com.hongjinqiu.nanhuprint.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element ref="{https://github.com/hongjinqiu/nanhu-print-java}css" minOccurs="0"/>
 *         &lt;element ref="{https://github.com/hongjinqiu/nanhu-print-java}params" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{https://github.com/hongjinqiu/nanhu-print-java}css-attribute"/>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="src" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cssAndParams"
})
@XmlRootElement(name = "img")
public class Img {

    @XmlElements({
        @XmlElement(name = "css", type = Css.class),
        @XmlElement(name = "params", type = Params.class)
    })
    protected List<Object> cssAndParams;
    @XmlAttribute(name = "id")
    @XmlSchemaType(name = "anySimpleType")
    protected String id;
    @XmlAttribute(name = "src")
    @XmlSchemaType(name = "anySimpleType")
    protected String src;
    @XmlAttribute(name = "cls")
    @XmlSchemaType(name = "anySimpleType")
    protected String cls;
    @XmlAttribute(name = "width")
    @XmlSchemaType(name = "anySimpleType")
    protected String width;
    @XmlAttribute(name = "height")
    @XmlSchemaType(name = "anySimpleType")
    protected String height;
    @XmlAttribute(name = "marginLeft")
    @XmlSchemaType(name = "anySimpleType")
    protected String marginLeft;
    @XmlAttribute(name = "marginTop")
    @XmlSchemaType(name = "anySimpleType")
    protected String marginTop;
    @XmlAttribute(name = "marginRight")
    @XmlSchemaType(name = "anySimpleType")
    protected String marginRight;
    @XmlAttribute(name = "marginBottom")
    @XmlSchemaType(name = "anySimpleType")
    protected String marginBottom;
    @XmlAttribute(name = "paddingLeft")
    @XmlSchemaType(name = "anySimpleType")
    protected String paddingLeft;
    @XmlAttribute(name = "paddingTop")
    @XmlSchemaType(name = "anySimpleType")
    protected String paddingTop;
    @XmlAttribute(name = "paddingRight")
    @XmlSchemaType(name = "anySimpleType")
    protected String paddingRight;
    @XmlAttribute(name = "paddingBottom")
    @XmlSchemaType(name = "anySimpleType")
    protected String paddingBottom;
    @XmlAttribute(name = "fontFamily")
    @XmlSchemaType(name = "anySimpleType")
    protected String fontFamily;
    @XmlAttribute(name = "fontStyle")
    @XmlSchemaType(name = "anySimpleType")
    protected String fontStyle;
    @XmlAttribute(name = "fontWeight")
    @XmlSchemaType(name = "anySimpleType")
    protected String fontWeight;
    @XmlAttribute(name = "textDecoration")
    @XmlSchemaType(name = "anySimpleType")
    protected String textDecoration;
    @XmlAttribute(name = "borderCollapse")
    @XmlSchemaType(name = "anySimpleType")
    protected String borderCollapse;
    @XmlAttribute(name = "borderSpacing")
    @XmlSchemaType(name = "anySimpleType")
    protected String borderSpacing;
    @XmlAttribute(name = "tableLayout")
    @XmlSchemaType(name = "anySimpleType")
    protected String tableLayout;
    @XmlAttribute(name = "textAlign")
    @XmlSchemaType(name = "anySimpleType")
    protected String textAlign;
    @XmlAttribute(name = "whiteSpace")
    @XmlSchemaType(name = "anySimpleType")
    protected String whiteSpace;
    @XmlAttribute(name = "wordWrap")
    @XmlSchemaType(name = "anySimpleType")
    protected String wordWrap;
    @XmlAttribute(name = "display")
    @XmlSchemaType(name = "anySimpleType")
    protected String display;
    @XmlAttribute(name = "visibility")
    @XmlSchemaType(name = "anySimpleType")
    protected String visibility;
    @XmlAttribute(name = "clear")
    @XmlSchemaType(name = "anySimpleType")
    protected String clear;
    @XmlAttribute(name = "zoom")
    @XmlSchemaType(name = "anySimpleType")
    protected String zoom;
    @XmlAttribute(name = "floatAlign")
    @XmlSchemaType(name = "anySimpleType")
    protected String floatAlign;
    @XmlAttribute(name = "fontSize")
    @XmlSchemaType(name = "anySimpleType")
    protected String fontSize;
    @XmlAttribute(name = "webkitBoxSizing")
    @XmlSchemaType(name = "anySimpleType")
    protected String webkitBoxSizing;
    @XmlAttribute(name = "mozBoxSizing")
    @XmlSchemaType(name = "anySimpleType")
    protected String mozBoxSizing;
    @XmlAttribute(name = "boxSizing")
    @XmlSchemaType(name = "anySimpleType")
    protected String boxSizing;
    @XmlAttribute(name = "minHeight")
    @XmlSchemaType(name = "anySimpleType")
    protected String minHeight;
    @XmlAttribute(name = "position")
    @XmlSchemaType(name = "anySimpleType")
    protected String position;
    @XmlAttribute(name = "lineHeight")
    @XmlSchemaType(name = "anySimpleType")
    protected String lineHeight;
    @XmlAttribute(name = "color")
    @XmlSchemaType(name = "anySimpleType")
    protected String color;
    @XmlAttribute(name = "borderTopWidth")
    @XmlSchemaType(name = "anySimpleType")
    protected String borderTopWidth;
    @XmlAttribute(name = "borderStyle")
    @XmlSchemaType(name = "anySimpleType")
    protected String borderStyle;
    @XmlAttribute(name = "borderTopColor")
    @XmlSchemaType(name = "anySimpleType")
    protected String borderTopColor;
    @XmlAttribute(name = "borderLeftWidth")
    @XmlSchemaType(name = "anySimpleType")
    protected String borderLeftWidth;
    @XmlAttribute(name = "borderLeftColor")
    @XmlSchemaType(name = "anySimpleType")
    protected String borderLeftColor;
    @XmlAttribute(name = "borderRightWidth")
    @XmlSchemaType(name = "anySimpleType")
    protected String borderRightWidth;
    @XmlAttribute(name = "borderRightColor")
    @XmlSchemaType(name = "anySimpleType")
    protected String borderRightColor;
    @XmlAttribute(name = "borderBottomWidth")
    @XmlSchemaType(name = "anySimpleType")
    protected String borderBottomWidth;
    @XmlAttribute(name = "borderBottomColor")
    @XmlSchemaType(name = "anySimpleType")
    protected String borderBottomColor;
    @XmlAttribute(name = "maxWidth")
    @XmlSchemaType(name = "anySimpleType")
    protected String maxWidth;
    @XmlAttribute(name = "left")
    @XmlSchemaType(name = "anySimpleType")
    protected String left;
    @XmlAttribute(name = "top")
    @XmlSchemaType(name = "anySimpleType")
    protected String top;
    @XmlAttribute(name = "right")
    @XmlSchemaType(name = "anySimpleType")
    protected String right;
    @XmlAttribute(name = "bottom")
    @XmlSchemaType(name = "anySimpleType")
    protected String bottom;
    @XmlAttribute(name = "verticalAlign")
    @XmlSchemaType(name = "anySimpleType")
    protected String verticalAlign;
    @XmlAttribute(name = "overflowX")
    @XmlSchemaType(name = "anySimpleType")
    protected String overflowX;
    @XmlAttribute(name = "overflowY")
    @XmlSchemaType(name = "anySimpleType")
    protected String overflowY;
    @XmlAttribute(name = "maxHeight")
    @XmlSchemaType(name = "anySimpleType")
    protected String maxHeight;
    @XmlAttribute(name = "backgroundColor")
    @XmlSchemaType(name = "anySimpleType")
    protected String backgroundColor;
    @XmlAttribute(name = "backgroundImage")
    @XmlSchemaType(name = "anySimpleType")
    protected String backgroundImage;
    @XmlAttribute(name = "backgroundImageOpacityByPdf")
    @XmlSchemaType(name = "anySimpleType")
    protected String backgroundImageOpacityByPdf;
    @XmlAttribute(name = "backgroundRepeat")
    @XmlSchemaType(name = "anySimpleType")
    protected String backgroundRepeat;
    @XmlAttribute(name = "backgroundSize")
    @XmlSchemaType(name = "anySimpleType")
    protected String backgroundSize;
    @XmlAttribute(name = "backgroundPositionX")
    @XmlSchemaType(name = "anySimpleType")
    protected String backgroundPositionX;
    @XmlAttribute(name = "backgroundPositionY")
    @XmlSchemaType(name = "anySimpleType")
    protected String backgroundPositionY;
    @XmlAttribute(name = "cellspacing")
    @XmlSchemaType(name = "anySimpleType")
    protected String cellspacing;
    @XmlAttribute(name = "cellpadding")
    @XmlSchemaType(name = "anySimpleType")
    protected String cellpadding;
    @XmlAttribute(name = "colspan")
    @XmlSchemaType(name = "anySimpleType")
    protected String colspan;
    @XmlAttribute(name = "rowspan")
    @XmlSchemaType(name = "anySimpleType")
    protected String rowspan;

    /**
     * Gets the value of the cssAndParams property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cssAndParams property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCssAndParams().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Css }
     * {@link Params }
     * 
     * 
     */
    public List<Object> getCssAndParams() {
        if (cssAndParams == null) {
            cssAndParams = new ArrayList<Object>();
        }
        return this.cssAndParams;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the src property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrc() {
        return src;
    }

    /**
     * Sets the value of the src property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrc(String value) {
        this.src = value;
    }

    /**
     * Gets the value of the cls property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCls() {
        return cls;
    }

    /**
     * Sets the value of the cls property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCls(String value) {
        this.cls = value;
    }

    /**
     * Gets the value of the width property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWidth(String value) {
        this.width = value;
    }

    /**
     * Gets the value of the height property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeight(String value) {
        this.height = value;
    }

    /**
     * Gets the value of the marginLeft property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarginLeft() {
        return marginLeft;
    }

    /**
     * Sets the value of the marginLeft property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarginLeft(String value) {
        this.marginLeft = value;
    }

    /**
     * Gets the value of the marginTop property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarginTop() {
        return marginTop;
    }

    /**
     * Sets the value of the marginTop property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarginTop(String value) {
        this.marginTop = value;
    }

    /**
     * Gets the value of the marginRight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarginRight() {
        return marginRight;
    }

    /**
     * Sets the value of the marginRight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarginRight(String value) {
        this.marginRight = value;
    }

    /**
     * Gets the value of the marginBottom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarginBottom() {
        return marginBottom;
    }

    /**
     * Sets the value of the marginBottom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarginBottom(String value) {
        this.marginBottom = value;
    }

    /**
     * Gets the value of the paddingLeft property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaddingLeft() {
        return paddingLeft;
    }

    /**
     * Sets the value of the paddingLeft property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaddingLeft(String value) {
        this.paddingLeft = value;
    }

    /**
     * Gets the value of the paddingTop property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaddingTop() {
        return paddingTop;
    }

    /**
     * Sets the value of the paddingTop property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaddingTop(String value) {
        this.paddingTop = value;
    }

    /**
     * Gets the value of the paddingRight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaddingRight() {
        return paddingRight;
    }

    /**
     * Sets the value of the paddingRight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaddingRight(String value) {
        this.paddingRight = value;
    }

    /**
     * Gets the value of the paddingBottom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaddingBottom() {
        return paddingBottom;
    }

    /**
     * Sets the value of the paddingBottom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaddingBottom(String value) {
        this.paddingBottom = value;
    }

    /**
     * Gets the value of the fontFamily property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFontFamily() {
        return fontFamily;
    }

    /**
     * Sets the value of the fontFamily property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFontFamily(String value) {
        this.fontFamily = value;
    }

    /**
     * Gets the value of the fontStyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFontStyle() {
        return fontStyle;
    }

    /**
     * Sets the value of the fontStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFontStyle(String value) {
        this.fontStyle = value;
    }

    /**
     * Gets the value of the fontWeight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFontWeight() {
        return fontWeight;
    }

    /**
     * Sets the value of the fontWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFontWeight(String value) {
        this.fontWeight = value;
    }

    /**
     * Gets the value of the textDecoration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextDecoration() {
        return textDecoration;
    }

    /**
     * Sets the value of the textDecoration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextDecoration(String value) {
        this.textDecoration = value;
    }

    /**
     * Gets the value of the borderCollapse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBorderCollapse() {
        return borderCollapse;
    }

    /**
     * Sets the value of the borderCollapse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBorderCollapse(String value) {
        this.borderCollapse = value;
    }

    /**
     * Gets the value of the borderSpacing property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBorderSpacing() {
        return borderSpacing;
    }

    /**
     * Sets the value of the borderSpacing property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBorderSpacing(String value) {
        this.borderSpacing = value;
    }

    /**
     * Gets the value of the tableLayout property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTableLayout() {
        return tableLayout;
    }

    /**
     * Sets the value of the tableLayout property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTableLayout(String value) {
        this.tableLayout = value;
    }

    /**
     * Gets the value of the textAlign property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextAlign() {
        return textAlign;
    }

    /**
     * Sets the value of the textAlign property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextAlign(String value) {
        this.textAlign = value;
    }

    /**
     * Gets the value of the whiteSpace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWhiteSpace() {
        return whiteSpace;
    }

    /**
     * Sets the value of the whiteSpace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWhiteSpace(String value) {
        this.whiteSpace = value;
    }

    /**
     * Gets the value of the wordWrap property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWordWrap() {
        return wordWrap;
    }

    /**
     * Sets the value of the wordWrap property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWordWrap(String value) {
        this.wordWrap = value;
    }

    /**
     * Gets the value of the display property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplay() {
        return display;
    }

    /**
     * Sets the value of the display property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplay(String value) {
        this.display = value;
    }

    /**
     * Gets the value of the visibility property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVisibility() {
        return visibility;
    }

    /**
     * Sets the value of the visibility property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVisibility(String value) {
        this.visibility = value;
    }

    /**
     * Gets the value of the clear property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClear() {
        return clear;
    }

    /**
     * Sets the value of the clear property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClear(String value) {
        this.clear = value;
    }

    /**
     * Gets the value of the zoom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZoom() {
        return zoom;
    }

    /**
     * Sets the value of the zoom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZoom(String value) {
        this.zoom = value;
    }

    /**
     * Gets the value of the floatAlign property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFloatAlign() {
        return floatAlign;
    }

    /**
     * Sets the value of the floatAlign property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFloatAlign(String value) {
        this.floatAlign = value;
    }

    /**
     * Gets the value of the fontSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFontSize() {
        return fontSize;
    }

    /**
     * Sets the value of the fontSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFontSize(String value) {
        this.fontSize = value;
    }

    /**
     * Gets the value of the webkitBoxSizing property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebkitBoxSizing() {
        return webkitBoxSizing;
    }

    /**
     * Sets the value of the webkitBoxSizing property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebkitBoxSizing(String value) {
        this.webkitBoxSizing = value;
    }

    /**
     * Gets the value of the mozBoxSizing property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMozBoxSizing() {
        return mozBoxSizing;
    }

    /**
     * Sets the value of the mozBoxSizing property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMozBoxSizing(String value) {
        this.mozBoxSizing = value;
    }

    /**
     * Gets the value of the boxSizing property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBoxSizing() {
        return boxSizing;
    }

    /**
     * Sets the value of the boxSizing property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBoxSizing(String value) {
        this.boxSizing = value;
    }

    /**
     * Gets the value of the minHeight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinHeight() {
        return minHeight;
    }

    /**
     * Sets the value of the minHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinHeight(String value) {
        this.minHeight = value;
    }

    /**
     * Gets the value of the position property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPosition() {
        return position;
    }

    /**
     * Sets the value of the position property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPosition(String value) {
        this.position = value;
    }

    /**
     * Gets the value of the lineHeight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLineHeight() {
        return lineHeight;
    }

    /**
     * Sets the value of the lineHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLineHeight(String value) {
        this.lineHeight = value;
    }

    /**
     * Gets the value of the color property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColor() {
        return color;
    }

    /**
     * Sets the value of the color property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColor(String value) {
        this.color = value;
    }

    /**
     * Gets the value of the borderTopWidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBorderTopWidth() {
        return borderTopWidth;
    }

    /**
     * Sets the value of the borderTopWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBorderTopWidth(String value) {
        this.borderTopWidth = value;
    }

    /**
     * Gets the value of the borderStyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBorderStyle() {
        return borderStyle;
    }

    /**
     * Sets the value of the borderStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBorderStyle(String value) {
        this.borderStyle = value;
    }

    /**
     * Gets the value of the borderTopColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBorderTopColor() {
        return borderTopColor;
    }

    /**
     * Sets the value of the borderTopColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBorderTopColor(String value) {
        this.borderTopColor = value;
    }

    /**
     * Gets the value of the borderLeftWidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBorderLeftWidth() {
        return borderLeftWidth;
    }

    /**
     * Sets the value of the borderLeftWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBorderLeftWidth(String value) {
        this.borderLeftWidth = value;
    }

    /**
     * Gets the value of the borderLeftColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBorderLeftColor() {
        return borderLeftColor;
    }

    /**
     * Sets the value of the borderLeftColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBorderLeftColor(String value) {
        this.borderLeftColor = value;
    }

    /**
     * Gets the value of the borderRightWidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBorderRightWidth() {
        return borderRightWidth;
    }

    /**
     * Sets the value of the borderRightWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBorderRightWidth(String value) {
        this.borderRightWidth = value;
    }

    /**
     * Gets the value of the borderRightColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBorderRightColor() {
        return borderRightColor;
    }

    /**
     * Sets the value of the borderRightColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBorderRightColor(String value) {
        this.borderRightColor = value;
    }

    /**
     * Gets the value of the borderBottomWidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBorderBottomWidth() {
        return borderBottomWidth;
    }

    /**
     * Sets the value of the borderBottomWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBorderBottomWidth(String value) {
        this.borderBottomWidth = value;
    }

    /**
     * Gets the value of the borderBottomColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBorderBottomColor() {
        return borderBottomColor;
    }

    /**
     * Sets the value of the borderBottomColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBorderBottomColor(String value) {
        this.borderBottomColor = value;
    }

    /**
     * Gets the value of the maxWidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxWidth() {
        return maxWidth;
    }

    /**
     * Sets the value of the maxWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxWidth(String value) {
        this.maxWidth = value;
    }

    /**
     * Gets the value of the left property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLeft() {
        return left;
    }

    /**
     * Sets the value of the left property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLeft(String value) {
        this.left = value;
    }

    /**
     * Gets the value of the top property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTop() {
        return top;
    }

    /**
     * Sets the value of the top property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTop(String value) {
        this.top = value;
    }

    /**
     * Gets the value of the right property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRight() {
        return right;
    }

    /**
     * Sets the value of the right property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRight(String value) {
        this.right = value;
    }

    /**
     * Gets the value of the bottom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBottom() {
        return bottom;
    }

    /**
     * Sets the value of the bottom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBottom(String value) {
        this.bottom = value;
    }

    /**
     * Gets the value of the verticalAlign property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVerticalAlign() {
        return verticalAlign;
    }

    /**
     * Sets the value of the verticalAlign property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVerticalAlign(String value) {
        this.verticalAlign = value;
    }

    /**
     * Gets the value of the overflowX property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOverflowX() {
        return overflowX;
    }

    /**
     * Sets the value of the overflowX property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOverflowX(String value) {
        this.overflowX = value;
    }

    /**
     * Gets the value of the overflowY property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOverflowY() {
        return overflowY;
    }

    /**
     * Sets the value of the overflowY property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOverflowY(String value) {
        this.overflowY = value;
    }

    /**
     * Gets the value of the maxHeight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxHeight() {
        return maxHeight;
    }

    /**
     * Sets the value of the maxHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxHeight(String value) {
        this.maxHeight = value;
    }

    /**
     * Gets the value of the backgroundColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackgroundColor() {
        return backgroundColor;
    }

    /**
     * Sets the value of the backgroundColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackgroundColor(String value) {
        this.backgroundColor = value;
    }

    /**
     * Gets the value of the backgroundImage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackgroundImage() {
        return backgroundImage;
    }

    /**
     * Sets the value of the backgroundImage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackgroundImage(String value) {
        this.backgroundImage = value;
    }

    /**
     * Gets the value of the backgroundImageOpacityByPdf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackgroundImageOpacityByPdf() {
        return backgroundImageOpacityByPdf;
    }

    /**
     * Sets the value of the backgroundImageOpacityByPdf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackgroundImageOpacityByPdf(String value) {
        this.backgroundImageOpacityByPdf = value;
    }

    /**
     * Gets the value of the backgroundRepeat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackgroundRepeat() {
        return backgroundRepeat;
    }

    /**
     * Sets the value of the backgroundRepeat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackgroundRepeat(String value) {
        this.backgroundRepeat = value;
    }

    /**
     * Gets the value of the backgroundSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackgroundSize() {
        return backgroundSize;
    }

    /**
     * Sets the value of the backgroundSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackgroundSize(String value) {
        this.backgroundSize = value;
    }

    /**
     * Gets the value of the backgroundPositionX property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackgroundPositionX() {
        return backgroundPositionX;
    }

    /**
     * Sets the value of the backgroundPositionX property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackgroundPositionX(String value) {
        this.backgroundPositionX = value;
    }

    /**
     * Gets the value of the backgroundPositionY property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackgroundPositionY() {
        return backgroundPositionY;
    }

    /**
     * Sets the value of the backgroundPositionY property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackgroundPositionY(String value) {
        this.backgroundPositionY = value;
    }

    /**
     * Gets the value of the cellspacing property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCellspacing() {
        return cellspacing;
    }

    /**
     * Sets the value of the cellspacing property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCellspacing(String value) {
        this.cellspacing = value;
    }

    /**
     * Gets the value of the cellpadding property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCellpadding() {
        return cellpadding;
    }

    /**
     * Sets the value of the cellpadding property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCellpadding(String value) {
        this.cellpadding = value;
    }

    /**
     * Gets the value of the colspan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColspan() {
        return colspan;
    }

    /**
     * Sets the value of the colspan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColspan(String value) {
        this.colspan = value;
    }

    /**
     * Gets the value of the rowspan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRowspan() {
        return rowspan;
    }

    /**
     * Sets the value of the rowspan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRowspan(String value) {
        this.rowspan = value;
    }

}
